# Build settings
markdown: kramdown
# remote_theme: pages-themes/hacker@v0.2.0
remote_theme: pages-themes/leap-day@v0.2.0

title: "Практика з ТРПЗ` 2023"
description: "Репозиторій з матеріалами для практики з 'Технологій розробки програмного забезпечення'"
show_downloads: "false"
