# Build settings
markdown: kramdown
remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/leap-day@v0.2.0

timezone: "Ukraine/Kyiv"
title: Практика з ТРПЗ-2023
author: Alexander Babich
description: "Репозиторій з матеріалами для практики з 'Технологій розробки програмного забезпечення'"

show_downloads: false

exclude: [README.md]

header_pages:
  - about.md
  - college.md
  - author.md
  
